function bubbleSort(arr) {
  const len = arr.length; // Obtener la longitud del arreglo para usarla como límite en el bucle
  let swapped; // Variable para controlar si se han realizado intercambios

  do {
    swapped = false; // Establecer la variable swapped en falso al inicio de cada iteración

    for (let i = 0; i < len - 1; i++) {
      // Bucle que recorre el arreglo
      if (arr[i] > arr[i + 1]) {
        // Comprobar si el elemento actual es mayor que el siguiente
        // Si es así, los elementos están en el orden incorrecto y necesitamos intercambiarlos
        const temp = arr[i]; // Guardar temporalmente el valor del elemento actual en una variable temporal
        arr[i] = arr[i + 1]; // Asignar el valor del siguiente elemento al elemento actual, realizando el intercambio
        arr[i + 1] = temp; // Asignar el valor temporal (valor original del elemento actual) al siguiente elemento, completando el intercambio
        swapped = true; // Establecer swapped en verdadero para indicar que se ha realizado al menos un intercambio
      }
    }
  } while (swapped); // Repetir el bucle mientras se hayan realizado intercambios en la iteración anterior

  return arr; // Devolver el arreglo ordenado
}

// Ejemplo de uso:
const unsortedArray = [64, 34, 25, 12, 22, 11, 90];
console.log(`Arreglo original: `,unsortedArray);

const sortedArray = bubbleSort(unsortedArray)
console.log(`Arreglo ordenado: `,sortedArray); // Resultado: [11, 12, 22, 25, 34, 64, 90]


function bubbleSortByProp(data, prop) {
  const n = data.length; // Obtener el número total de elementos en la lista.
  for (let i = 0; i < n; i++) {
      // El último i elementos ya están en su posición correcta.
      // Bucle externo que recorre la lista de izquierda a derecha.
      for (let j = 0; j < n - i - 1; j++) {
          // Bucle interno que recorre la lista de izquierda a derecha hasta el elemento n - i - 1.
          // Si el nombre actual es mayor que el siguiente nombre, intercambiarlos.
          if (data[j][prop] > data[j + 1][prop]) {
              const temp = data[j]; // Guardar temporalmente el objeto actual en una variable temporal.
              data[j] = data[j + 1]; // Intercambiar el objeto actual con el siguiente objeto en la lista.
              data[j + 1] = temp; // Colocar el objeto temporal en la posición del objeto siguiente, completando el intercambio.
          }
      }
  }
  return data; // Retorna la lista de objetos ordenada por el campo "prop"

}

const characters = [
  {
      "name": "Hermione Granger",
      "alternate_names": [],
      "species": "human",
      "gender": "female",
      "house": "Gryffindor",
      "dateOfBirth": "19-09-1979",
      "yearOfBirth": 1979,
      "wizard": true,
      "ancestry": "muggleborn",
      "eyeColour": "brown",
      "hairColour": "brown",
      "wand": {
          "wood": "vine",
          "core": "dragon heartstring",
          "length": ""
      },
      "patronus": "otter",
      "hogwartsStudent": true,
      "hogwartsStaff": false,
      "actor": "Emma Watson",
      "alternate_actors": [],
      "alive": true,
      "image": "http://hp-api.herokuapp.com/images/hermione.jpeg"
  },
  {
      "name": "Ron Weasley",
      "alternate_names": [
          "Dragomir Despard"
      ],
      "species": "human",
      "gender": "male",
      "house": "Gryffindor",
      "dateOfBirth": "01-03-1980",
      "yearOfBirth": 1980,
      "wizard": true,
      "ancestry": "pure-blood",
      "eyeColour": "blue",
      "hairColour": "red",
      "wand": {
          "wood": "willow",
          "core": "unicorn tail-hair",
          "length": 14
      },
      "patronus": "Jack Russell terrier",
      "hogwartsStudent": true,
      "hogwartsStaff": false,
      "actor": "Rupert Grint",
      "alternate_actors": [],
      "alive": true,
      "image": "http://hp-api.herokuapp.com/images/ron.jpg"
    },
    {
      "name": "Harry Potter",
      "alternate_names": [],
      "species": "human",
      "gender": "male",
      "house": "Gryffindor",
      "dateOfBirth": "31-07-1980",
      "yearOfBirth": 1980,
      "wizard": true,
      "ancestry": "half-blood",
      "eyeColour": "green",
      "hairColour": "black",
      "wand": {
          "wood": "holly",
          "core": "phoenix feather",
          "length": 11
      },
      "patronus": "stag",
      "hogwartsStudent": true,
      "hogwartsStaff": false,
      "actor": "Daniel Radcliffe",
      "alternate_actors": [],
      "alive": true,
      "image": "http://hp-api.herokuapp.com/images/harry.jpg"
  },
  // },
  // {
  //     "name": "Draco Malfoy",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "05-06-1980",
  //     "yearOfBirth": 1980,
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "grey",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "hawthorn",
  //         "core": "unicorn tail-hair",
  //         "length": 10
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Tom Felton",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/draco.jpg"
  // },
  // {
  //     "name": "Cedric Diggory",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": 1977,
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "grey",
  //     "hairColour": "brown",
  //     "wand": {
  //         "wood": "ash",
  //         "core": "unicorn hair",
  //         "length": 12.25
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Robert Pattinson",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": "http://hp-api.herokuapp.com/images/cedric.png"
  // },
  // {
  //     "name": "Cho Chang",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "brown",
  //     "hairColour": "black",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "swan",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Katie Leung",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/cho.jpg"
  // },
  // {
  //     "name": "Neville Longbottom",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "30-07-1980",
  //     "yearOfBirth": 1980,
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "cherry",
  //         "core": "unicorn tail-hair",
  //         "length": 13
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Matthew Lewis",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/neville.jpg"
  // },
  // {
  //     "name": "Luna Lovegood",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "13-02-1981",
  //     "yearOfBirth": 1981,
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "grey",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "hare",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Evanna Lynch",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/luna.jpg"
  // },
  // {
  //     "name": "Ginny Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "11-08-1981",
  //     "yearOfBirth": 1981,
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "brown",
  //     "hairColour": "red",
  //     "wand": {
  //         "wood": "yew",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "horse",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Bonnie Wright",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/ginny.jpg"
  // },
  // {
  //     "name": "Vincent Crabbe",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "black",
  //     "hairColour": "black",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Jamie Waylett",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": "http://hp-api.herokuapp.com/images/crabbe.jpg"
  // },
  // {
  //     "name": "Gregory Goyle",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "brown",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Josh Herdman",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": "http://hp-api.herokuapp.com/images/goyle.jpg"
  // },
  // {
  //     "name": "Percy Weasley",
  //     "alternate_names": [
  //         "Perce",
  //         "Percy Ignatius Weasley",
  //         "Weatherby"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "red",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Chris Rankin",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Fred Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "red",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "James Phelps",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": ""
  // },
  // {
  //     "name": "George Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "red",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Oliver Phelps",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Lee Jordan",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Luke Youngblood",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Hannah Abbott",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Charlotte Skeoch",
  //     "alternate_actors": [
  //         "Louisa Warren"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Susan Bones",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Eleanor Columbus",
  //     "alternate_actors": [
  //         "Emma Jayne-Corboz"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Terry Boot",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Kevin Lee Yi",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Mandy Brocklehurst",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Christina Petrou",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Lavender Brown",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Kathleen Cauley",
  //     "alternate_actors": [
  //         "Jennifer Smith",
  //         "Jessie Cave"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Millicent Bulstrode",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Helen Stuart",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Justin Finch-Fletchley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "muggleborn",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Edward Randell",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Seamus Finnegan",
  //     "alternate_names": [
  //         "O'Flaherty"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "",
  //     "hairColour": "sandy",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Devon Murray",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Morag MacDougal",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Lily Moon",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Theodore Nott",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Pansy Parkinson",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Genevieve Gaunt",
  //     "alternate_actors": [
  //         "Lauren Shotton",
  //         "Scarlett Byrne"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Parvati Patil",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Sitara Shah",
  //     "alternate_actors": [
  //         "Shefali Chowdhury"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Padma Patil",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Sharon Sandhu",
  //     "alternate_actors": [
  //         "Afshan Azad"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Sally-Anne Perks",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Lisa Turpin",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Blaise Zabini",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Louis Cordice",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Oliver Wood",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Sean Biggerstaff",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Angelina Johnson",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Danielle Tabor",
  //     "alternate_actors": [
  //         "Tiana Benjamin"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Marcus Flint",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Jamie Yeates",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Alicia Spinet",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Leilah Sutherland",
  //     "alternate_actors": [
  //         "Rochelle Douglas"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Katie Bell",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Emily Dale",
  //     "alternate_actors": [
  //         "Georgina Leonidas"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Adrian Pucey",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Scot Fearn",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Miles Bletchley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "David Churchyard",
  //     "alternate_actors": [
  //         "Amy Puglia"
  //     ],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Terrence Higgs",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Will Theakston",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Colin Creevey",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "muggleborn",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Hugh Mitchell",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": ""
  // },
  // {
  //     "name": "Milicent Bullstroude",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "black",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Helen Stuart",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Ernie Macmillan",
  //     "alternate_names": [
  //         "Ernest Macmillan"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "blond",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "boar",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Louis Doyle",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Penelope Clearwater",
  //     "alternate_names": [
  //         "Penny"
  //     ],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Gemma Padley",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Derek",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Cassius Warrington",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Ashley Hull",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Graham Montague",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Peregrine Derrick",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Lucian Bole",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Dennis Creevey",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "muggleborn",
  //     "eyeColour": "",
  //     "hairColour": "brown",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Stewart Ackerley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Malcolm Baddock",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Eleanor Branstone",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Owen Cauldwell",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Emma Dobbs",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Laura Madley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Natalie McDonald",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Graham Pritchard",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Orla Quirke",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Kevin Whitby",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Eloise Midgen",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Samantha Clinch",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Fawcett",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Alex Argenti",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Summers",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Stebbins",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Anthony Goldstein",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Euan Abercrombie",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Rose Zeller",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Patricia Stimpson",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Kenneth Towler",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Vicky Frobisher",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Geoffrey Hooper",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Michael Corner",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Ryan Nelson",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Zacharias Smith",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "blond",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Nick Shirm",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Barnabas the Barmy",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": ""
  // },
  // {
  //     "name": "Andrew Kirke",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Jack Sloper",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Summerby",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Marietta Edgecombe",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Bradley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Roger Davies",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Henry Lloyd-Hughes",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Eddie Carmichael",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Daphne Greengrass",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Romilda Vane",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "dark",
  //     "hairColour": "black",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Anna Shaffer",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Cormac McLaggen",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Freddie Stroma",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Marcus Belby",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Ravenclaw",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Robert Knox",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Tiberius",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": false,
  //     "image": ""
  // },
  // {
  //     "name": "Demelza Robins",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Katy Huxley-Golden",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Jimmy Peakes",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Ritchie Coote",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Ashley Virgil",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Melinda Bobbin",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Leanne",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Isabella Laughland",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Vaisey",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "dark",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Harper",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Urquhart",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Cadwallader",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Hufflepuff",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "James Potter",
  //     "alternate_names": [
  //         "James Sirius Potter"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "",
  //     "hairColour": "",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Will Dunn",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Albus Severus Potter",
  //     "alternate_names": [
  //         "Al"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "green",
  //     "hairColour": "black",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Arthur Bowen",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Rose Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "Gryffindor",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "",
  //     "hairColour": "red",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Helena Barlow",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Hugo Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "half-blood",
  //     "eyeColour": "",
  //     "hairColour": "brown",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Ryan Turner",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Scorpius Malfoy",
  //     "alternate_names": [
  //         "Scorpius Hyperion Malfoy"
  //     ],
  //     "species": "human",
  //     "gender": "male",
  //     "house": "Slytherin",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "pure-blood",
  //     "eyeColour": "grey",
  //     "hairColour": "blond",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "Bertie Gilbert",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // },
  // {
  //     "name": "Victoire Weasley",
  //     "alternate_names": [],
  //     "species": "human",
  //     "gender": "female",
  //     "house": "",
  //     "dateOfBirth": "",
  //     "yearOfBirth": "",
  //     "wizard": true,
  //     "ancestry": "",
  //     "eyeColour": "",
  //     "hairColour": "blonde",
  //     "wand": {
  //         "wood": "",
  //         "core": "",
  //         "length": ""
  //     },
  //     "patronus": "",
  //     "hogwartsStudent": true,
  //     "hogwartsStaff": false,
  //     "actor": "",
  //     "alternate_actors": [],
  //     "alive": true,
  //     "image": ""
  // }
]
// console.log("characters",characters)
const arrayCharacters = bubbleSortByProp(characters, "yearOfBirth")

console.log("arrayCharacters",arrayCharacters)